
CREATE ROLE tdm LOGIN PASSWORD 'tdm' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

--CREATE DATABASE "TDMDB" WITH OWNER = tdm ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;
CREATE DATABASE "TDMDB" WITH OWNER = tdm ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1 TEMPLATE = template0  lc_collate='en_US.utf8' lc_ctype='en_US.utf8' ;
